### ISSUE TITLE
Transliterate

### ISSUE THREAD

**Issue by watzon** [vladfaust/i18n.cr#4]
It would be nice to have transliteration built in as well.

```crystal
I18n.transliterate('Ærøskøbing') # => "AEroskobing"
```
I am working on porting `ActiveSupport` to Crystal and would like to use this i18n, but I need transliteration support. For reference, [this](https://github.com/svenfuchs/i18n/blob/96f6e705d6c71ebda6d1a0acd47ea09810024120/lib/i18n/backend/transliterator.rb) is the way the Ruby lib does it

**Comment by vladfaust** [comment]
Hello, @watzon! I honestly had never used something similar to `transliterate` and I do not need for any of my projects. The project is MIT, so you could use the code as you wish. But no need for reinventing bicycle, right? 

I propose you to create a separate shard called `t13n.cr`, which will require `i18n.cr` as dependency, and include both into your `ActiveSupport` project. I would add a link to `t13n.cr` module into `README`.
